### PR TITLE
[CW] [00000] AG Smoke Test for Versions and Asset Fingerprints

### PR DESCRIPTION
**Pull request by c0**
- Display a list of versions for each prod server in AG.
- Display the asset fingerprint for each prod server and QA.

Requires Hubot to be in the data center.

I'm not sure if It needs to be hooked up or if Hubot just knows about it.

### CODE REVIEW

**Comment by pasha** [comment]
:+1: looks good, not sure how would i test this.

**Comment by c0** [comment]
@atljeremy can you elaborate why this was closed? It was waiting to be merged until Hubot is inside the network.

**Comment by atljeremy** [comment]
Because this repo has been completely emptied and is being repurposed with a new Hubot build and custom scripts. It was not being used at all so the PR was pending to be merge into something that wasn't even being used. I've started an initiative to get a bot going and will certainly allow custom scripts to be added to it but this script hasn't been tested with the new Hubot build so I closed it for now so that no one merges it. We can re-open it after I've got the bot up and running on the bot machine with Jenkins auto building and deploying new scripts/updates to the bot machine.

I'll ping you about re-opening this after all of this is done and the bot is ready for custom scripts. Sorry for not specify all of this before closing. Honestly thought no one was even watching this anymore since this PR is 9 months old. :)

**Comment by c0** [comment]
Thanks for elaborating. I've been waiting for a real Hubot for a long time :)

**Pull request closed without merging**
